### ISSUE TITLE
项目依赖jdk版本是18吗？

### ISSUE THREAD

**Issue by CrazyShado** [gx304419380/ai-service#12]
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x000000017a85ea63, pid=12146, tid=10755
#
# JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.15.1+2) (build 11.0.15.1+2-LTS-10)
# Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.15.1+2-LTS-10, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libpaddle_inference.dylib+0x1ba63]  __cxx_global_var_init.1118+0x93
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

**Comment by gx304419380** [comment]
我本地是jdk17
